// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class 1SuperAdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 11LoginPage() {
    driver.get("https://192.168.0.100:8443/auth?method=LOGOUT");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("admin@istarindia.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void 12createOrganization() {
    driver.get("https://192.168.0.100:8443/SUPER_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Create Organization")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("SaleskenTesting");
    driver.findElement(By.id("url")).sendKeys("http://saleskenTest.ai.com");
    driver.findElement(By.id("contact_name")).sendKeys("Rohit kumar saini");
    driver.findElement(By.id("contact_email")).sendKeys("rohitsainincr@gmail.com");
    driver.findElement(By.id("employee_count")).sendKeys("100");
    driver.findElement(By.id("contact_phone")).sendKeys("919568381047");
    {
      WebElement dropdown = driver.findElement(By.id("industry_select"));
      dropdown.findElement(By.xpath("//option[. = 'Information Technology/IT']")).click();
    }
    driver.findElement(By.id("contact_person_name")).sendKeys("Rohit Kumar Saini");
    driver.findElement(By.id("contact_person_email")).sendKeys("rohitkumarsaini@gmail.com");
    driver.findElement(By.id("phone")).sendKeys("918090784203");
    driver.findElement(By.cssSelector(".create_org")).click();
  }
  @Test
  public void 13LogOutPage() {
    driver.get("https://192.168.0.100:8443/SUPER_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.cssSelector(".istar_font-20")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(3)")).click();
    driver.close();
  }
}
