// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class 2ManagerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 21LoginPage() {
    driver.get("https://192.168.0.100:8443/auth?method=LOGOUT");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("rohitkumarsaini@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
  }
  @Test
  public void 22CreateTeam() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Team")).click();
    driver.findElement(By.linkText("Create Team")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("SoftDevTest");
    driver.findElement(By.id("description")).sendKeys("to write code and test");
    driver.findElement(By.id("create_team")).click();
    driver.findElement(By.cssSelector(".swal-button")).click();
  }
  @Test
  public void 23AddProduct() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/teams.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Product")).click();
    driver.findElement(By.cssSelector(".btn-1")).click();
    driver.findElement(By.id("name")).sendKeys("istarAnalysis");
    driver.findElement(By.id("create_product")).click();
  }
  @Test
  public void 24AddSignal() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Product")).click();
    driver.findElement(By.id("588")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("i am calling you from ec council");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 88 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("am I a speaking with");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 88 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    {
      WebElement dropdown = driver.findElement(By.id("signalName_-1"));
      dropdown.findElement(By.xpath("//option[. = 'Lead']")).click();
    }
    driver.findElement(By.id("signalValue_-1")).sendKeys("are you studying");
    driver.findElement(By.id("submit_product")).click();
  }
  @Test
  public void 25AddPipeline() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Pipeline")).click();
    driver.findElement(By.linkText("New Pipeline")).click();
    driver.findElement(By.cssSelector(".create-pipeline-name")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".create-pipeline-name"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'salesken'}", element);
    }
  }
  @Test
  public void 26AddTeamInPipeline() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Pipeline")).click();
    driver.findElement(By.cssSelector(".fa-edit")).click();
    driver.findElement(By.cssSelector(".button:nth-child(1)")).click();
    driver.findElement(By.id("addteam")).click();
    {
      WebElement dropdown = driver.findElement(By.id("addteam"));
      dropdown.findElement(By.xpath("//option[. = 'Select Team']")).click();
    }
    driver.findElement(By.id("addteam")).click();
  }
  @Test
  public void 27AddProductInPipeline() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Pipeline")).click();
    driver.findElement(By.cssSelector(".fa-edit")).click();
    driver.findElement(By.cssSelector(".button:nth-child(3)")).click();
    driver.findElement(By.id("addproduct")).click();
    {
      WebElement dropdown = driver.findElement(By.id("addproduct"));
      dropdown.findElement(By.xpath("//option[. = 'Select Product']")).click();
    }
    driver.findElement(By.id("addproduct")).click();
  }
  @Test
  public void 28AddStageInPipeline() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.findElement(By.linkText("Pipeline")).click();
    driver.findElement(By.cssSelector(".fa-edit")).click();
    driver.findElement(By.cssSelector(".add-column")).click();
    driver.findElement(By.cssSelector(".add-task-icon")).click();
    driver.findElement(By.cssSelector(".fa-phone")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#stage_column_894 > .add-card .material-icons")).click();
    driver.findElement(By.cssSelector(".popover-body > .istar_button-transparent:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".add-column")).click();
    driver.findElement(By.cssSelector("#stage_column_895 > .add-card .material-icons")).click();
    driver.findElement(By.cssSelector(".purple")).click();
  }
  @Test
  public void 29AddLead() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("lead_company_name")).sendKeys("Google");
    driver.findElement(By.id("lead_city")).sendKeys("Bangalore");
    driver.findElement(By.id("lead_country")).sendKeys("India");
    driver.findElement(By.id("lead_address")).sendKeys("Bangalore.kt,india");
    driver.findElement(By.id("lead_state")).sendKeys("karanataka ");
    driver.findElement(By.id("lead_pincode")).sendKeys("4533");
    driver.findElement(By.cssSelector(".istar_modal-btn-danger")).click();
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("lead_company_name")).sendKeys("Amazon");
    {
      WebElement dropdown = driver.findElement(By.id("lead_source"));
      dropdown.findElement(By.xpath("//option[. = 'MARKETING']")).click();
    }
    driver.findElement(By.id("lead_city")).sendKeys("bangalore");
    driver.findElement(By.id("lead_address")).sendKeys("bangalore,karantaka,india");
    driver.findElement(By.id("lead_country")).sendKeys("india");
    driver.findElement(By.id("lead_state")).sendKeys("karanataka ");
    driver.findElement(By.id("lead_pincode")).sendKeys("234");
    driver.findElement(By.cssSelector(".istar_modal-btn-danger")).click();
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
  }
  @Test
  public void 210AddSalePersonInformationInAddLead() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector("#\\39 3174 .material-icons")).click();
    driver.findElement(By.cssSelector(".show > .dropdown-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".istar_add-icon")).click();
    driver.findElement(By.id("new_name")).sendKeys("Rajneesh");
    driver.findElement(By.id("new_email")).sendKeys("saletech@salesken.ai");
    driver.findElement(By.id("new_phone_number")).sendKeys("+919568381047");
    driver.findElement(By.cssSelector(".justify-content-end > .p-1")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".istar-allocate-lead-submit"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector("#\\39 3176 .material-icons")).click();
    driver.findElement(By.cssSelector(".show > .dropdown-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".istar_add-icon")).click();
    driver.findElement(By.id("new_name")).sendKeys("Rohit");
    driver.findElement(By.id("new_email")).sendKeys("tech3@salesken.ai");
    driver.findElement(By.id("new_phone_number")).sendKeys("+917624941620");
    {
      WebElement element = driver.findElement(By.cssSelector(".justify-content-end > .p-1"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".justify-content-end > .p-1")).click();
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
  }
  @Test
  public void 211AddAllocationIteamsInAddLead() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector("#\\39 3176 .material-icons")).click();
    driver.findElement(By.cssSelector(".show > .dropdown-item:nth-child(7)")).click();
    driver.findElement(By.cssSelector(".editLeadPipelines")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".editLeadPipelines"));
      dropdown.findElement(By.xpath("//option[. = 'salesken']")).click();
    }
    driver.findElement(By.cssSelector(".editLeadPipelines")).click();
    driver.findElement(By.cssSelector(".justify-content-end > .p-1")).click();
    driver.findElement(By.id("editLeadDateandTime")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".istar-allocate-lead-submit"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    driver.findElement(By.cssSelector(".istar-allocate-lead-submit")).click();
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
  }
  @Test
  public void 212TodayCompletedTask() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.id("todaysTaskFilter")).click();
    {
      WebElement dropdown = driver.findElement(By.id("todaysTaskFilter"));
      dropdown.findElement(By.xpath("//option[. = 'Completed']")).click();
    }
    driver.findElement(By.id("todaysTaskFilter")).click();
  }
  @Test
  public void 213TodayScheduledTask() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.id("todaysTaskFilter")).click();
    {
      WebElement dropdown = driver.findElement(By.id("todaysTaskFilter"));
      dropdown.findElement(By.xpath("//option[. = 'Scheduled']")).click();
    }
    driver.findElement(By.id("todaysTaskFilter")).click();
  }
  @Test
  public void 214TodayOngoingTask() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.id("todaysTaskFilter")).click();
    {
      WebElement dropdown = driver.findElement(By.id("todaysTaskFilter"));
      dropdown.findElement(By.xpath("//option[. = 'Ongoing']")).click();
    }
    driver.findElement(By.id("todaysTaskFilter")).click();
  }
  @Test
  public void 215TodayAnalyzingTask() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.id("todaysTaskFilter")).click();
    {
      WebElement dropdown = driver.findElement(By.id("todaysTaskFilter"));
      dropdown.findElement(By.xpath("//option[. = 'Analyzing']")).click();
    }
    driver.findElement(By.id("todaysTaskFilter")).click();
  }
  @Test
  public void 216TodayAllTask() {
    driver.get("https://192.168.0.100:8443/SALES_MANAGER/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Dashboard")).click();
  }
  @Test
  public void 217Reports() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Reports")).click();
    driver.findElement(By.id("Disposition-tab")).click();
    driver.findElement(By.id("SignalAnalysis-tab")).click();
    driver.findElement(By.id("myTabContent")).click();
    driver.findElement(By.id("Productivity-tab")).click();
    driver.findElement(By.id("TalkRatio-tab")).click();
    driver.findElement(By.id("Mentions-tab")).click();
    driver.findElement(By.id("FollowUps-tab")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("Objections-tab")).click();
  }
  @Test
  public void 218Notifications() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.cssSelector(".istar_font-28")).click();
    driver.findElement(By.id("notification_read_more")).click();
  }
  @Test
  public void 219Logout() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.cssSelector(".position-relative > .d-flex .btn")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
}
