// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class 3ITAdminTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 31LoginPage() {
    driver.get("https://192.168.0.100:8443/index.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("rohitkumarsaini@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
  }
  @Test
  public void 32CreateTeam() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.cssSelector(".istar_onclick")).click();
    driver.findElement(By.id("name")).sendKeys("SoftDevTest");
    driver.findElement(By.id("description")).sendKeys("to write code and test");
    driver.findElement(By.id("create_team")).click();
    driver.findElement(By.cssSelector(".swal-button")).click();
  }
  @Test
  public void 33AddUser() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.linkText("Users")).click();
    driver.findElement(By.cssSelector(".istar_btn-1")).click();
    driver.findElement(By.id("user_name")).sendKeys("Rajneesh kumar");
    driver.findElement(By.name("email")).sendKeys("techsale1@salesken.ai");
    driver.findElement(By.name("phone")).sendKeys("919568381047");
    driver.findElement(By.cssSelector("#ms-list-2 > button")).click();
    driver.findElement(By.cssSelector("li:nth-child(18) > label")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".istar_btn-1")).click();
    driver.findElement(By.id("user_name")).sendKeys("Sunil");
    driver.findElement(By.name("email")).sendKeys("techsale8@salesken.ai");
    driver.findElement(By.name("phone")).sendKeys("919568381047");
    driver.findElement(By.cssSelector("#ms-list-4 > button")).click();
    driver.findElement(By.cssSelector("li:nth-child(18) > label")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
  }
  @Test
  public void 34AddOrganizationConfigurationSetting() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Settings")).click();
    driver.findElement(By.cssSelector(".istar_save-button")).click();
  }
  @Test
  public void 35AddManagerHierarchy() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.linkText("Manager")).click();
    driver.findElement(By.cssSelector(".fa-plus")).click();
    driver.findElement(By.id("managerList")).click();
  }
  @Test
  public void 36Logout() {
    driver.get("https://192.168.0.100:8443/IT_ADMIN/dashboard.jsp");
    driver.manage().window().setSize(new Dimension(1280, 728));
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
}
