// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class SeleniumTestCaseTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void 1CreateOrganization() {
    driver.get("http://192.168.0.100:8080/index.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("admin@istarindia.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Create Organization")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("SaleskenTest");
    driver.findElement(By.id("url")).sendKeys("http://salesken.ai.com");
    driver.findElement(By.id("contact_name")).sendKeys("Rohit saini");
    driver.findElement(By.id("contact_email")).sendKeys("rohitsainincr1@gmail.com");
    driver.findElement(By.id("employee_count")).sendKeys("100");
    driver.findElement(By.id("contact_phone")).sendKeys("918090784203");
    {
      WebElement dropdown = driver.findElement(By.id("industry_select"));
      dropdown.findElement(By.xpath("//option[. = 'Industrial Automation']")).click();
    }
    driver.findElement(By.id("contact_person_name")).sendKeys("Rohit Saini");
    driver.findElement(By.id("contact_person_email")).sendKeys("rohitsainincr11@gmail.com");
    driver.findElement(By.id("phone")).sendKeys("9918873914");
    driver.findElement(By.cssSelector(".create_org")).click();
    driver.findElement(By.cssSelector(".istar_font-20")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(3)")).click();
  }
  @Test
  public void 2CreateTeamandUser() {
    driver.get("http://192.168.0.100:8080/auth?method=LOGOUT");
    driver.manage().window().setSize(new Dimension(798, 558));
    driver.findElement(By.name("email")).sendKeys("rohitsainincr11@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
    driver.findElement(By.linkText("Team")).click();
    driver.findElement(By.linkText("Create Team")).click();
    driver.findElement(By.id("name")).sendKeys("SoftwareDeveloperR");
    driver.findElement(By.id("description")).sendKeys("to write the code");
    driver.findElement(By.id("create_team")).click();
    driver.findElement(By.cssSelector(".swal-button")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
    driver.findElement(By.linkText("Users")).click();
    driver.findElement(By.cssSelector(".istar_btn-1")).click();
    driver.findElement(By.id("user_name")).sendKeys("Ajneesh kumar");
    driver.findElement(By.name("email")).sendKeys("albc@gamil.com");
    driver.findElement(By.name("phone")).sendKeys("9876235467");
    driver.findElement(By.name("pincode")).sendKeys("6754");
    driver.findElement(By.name("addressline1")).sendKeys("bangalore");
    driver.findElement(By.cssSelector("#ms-list-2 > button")).click();
    driver.findElement(By.cssSelector("li:nth-child(18) > label")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("user_name")).sendKeys("Harish");
    driver.findElement(By.name("email")).sendKeys("kjm@gmail.ai.com");
    driver.findElement(By.name("phone")).sendKeys("8657345111");
    driver.findElement(By.name("pincode")).sendKeys("1234");
    driver.findElement(By.name("addressline1")).sendKeys("bangalore");
    driver.findElement(By.cssSelector("#ms-list-2 > button")).click();
    driver.findElement(By.cssSelector("li:nth-child(18) > label")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.linkText("Manager")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
  @Test
  public void 3Product() {
    driver.get("http://192.168.0.100:8080/index.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("rohitsainincr11@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) .menu_icon")).click();
    driver.findElement(By.cssSelector(".btn-1")).click();
    driver.findElement(By.id("name")).sendKeys("ProductSalesken Analysis");
    driver.findElement(By.id("create_product")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".list-signals > .file-holder")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("i am calling you from ec council");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("you had enquired on our website about");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("hello this is");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("can you just let me know about your profile");
    {
      WebElement dropdown = driver.findElement(By.id("signalName_4061"));
      dropdown.findElement(By.xpath("//option[. = 'Lead']")).click();
    }
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    {
      WebElement dropdown = driver.findElement(By.id("signalName_-1"));
      dropdown.findElement(By.xpath("//option[. = 'Lead']")).click();
    }
    driver.findElement(By.id("signalValue_-1")).sendKeys("are you in a job");
    driver.findElement(By.id("signalColor_4104")).sendKeys("#ff00ff");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalName_-1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("signalName_-1"));
      dropdown.findElement(By.xpath("//option[. = 'custom_signal_name']")).click();
    }
    driver.findElement(By.cssSelector(".addNewSignal")).click();
    driver.findElement(By.cssSelector(".addNewSignal")).click();
    driver.findElement(By.id("signalValue_-1")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("online interactive training");
    driver.findElement(By.cssSelector(".addNewSignal")).click();
    {
      WebElement element = driver.findElement(By.id("submit_product"));
      Action builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Action builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalName_-1")).click();
    {
      WebElement dropdown = driver.findElement(By.id("signalName_-1"));
      dropdown.findElement(By.xpath("//option[. = 'Value Proposition']")).click();
    }
    driver.findElement(By.id("signalName_-1")).click();
    driver.findElement(By.id("signalValue_-1")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("certified instructors");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    {
      WebElement dropdown = driver.findElement(By.id("signalName_-1"));
      dropdown.findElement(By.xpath("//option[. = 'Need Investigation']")).click();
    }
    driver.findElement(By.id("signalValue_-1")).sendKeys("what are your interests");
    driver.findElement(By.id("signalName_4107")).click();
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector("#\\35 16 > .fa-pencil-square-o")).click();
    driver.findElement(By.linkText("Signals")).click();
    driver.findElement(By.cssSelector(".font-36")).click();
    driver.findElement(By.id("signalValue_-1")).sendKeys("training certification course material and voucher");
    {
      WebElement dropdown = driver.findElement(By.id("signalName_4108"));
      dropdown.findElement(By.xpath("//option[. = 'Features']")).click();
    }
    driver.findElement(By.id("signalColor_4108")).sendKeys("#8000ff");
    driver.findElement(By.id("submit_product")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
  @Test
  public void 4Pipeline() {
    driver.get("http://192.168.0.100:8080/index.jsp");
    driver.manage().window().setSize(new Dimension(1296, 744));
    driver.findElement(By.name("email")).sendKeys("rohitsainincr11@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".position-relative > .d-flex .btn")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
    driver.findElement(By.linkText("Pipeline")).click();
    driver.findElement(By.linkText("New Pipeline")).click();
    driver.findElement(By.cssSelector(".create-pipeline-name")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".create-pipeline-name"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = 'salesken'}", element);
    }
    driver.findElement(By.cssSelector(".pipe-card-container")).click();
    driver.findElement(By.cssSelector(".button:nth-child(1)")).click();
    driver.findElement(By.id("addteam")).click();
    {
      WebElement dropdown = driver.findElement(By.id("addteam"));
      dropdown.findElement(By.xpath("//option[. = 'Select Team']")).click();
    }
    driver.findElement(By.id("addteam")).click();
    driver.findElement(By.cssSelector(".button:nth-child(3)")).click();
    driver.findElement(By.id("addproduct")).click();
    {
      WebElement dropdown = driver.findElement(By.id("addproduct"));
      dropdown.findElement(By.xpath("//option[. = 'Select Product']")).click();
    }
    driver.findElement(By.id("addproduct")).click();
    driver.findElement(By.cssSelector(".add-column")).click();
    driver.findElement(By.cssSelector(".add-task-icon")).click();
    driver.findElement(By.cssSelector(".fa-phone")).click();
    driver.findElement(By.cssSelector(".add-task-icon")).click();
    driver.findElement(By.cssSelector(".popover-body > .istar_button-transparent:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".add-task-icon")).click();
    driver.findElement(By.cssSelector(".purple")).click();
    driver.findElement(By.cssSelector(".position-relative > .d-flex .btn")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
  @Test
  public void 5AddLead() {
    driver.get("http://192.168.0.100:8080/index.jsp");
    driver.manage().window().setSize(new Dimension(798, 558));
    driver.findElement(By.name("email")).sendKeys("rohitsainincr11@gmail.com");
    driver.findElement(By.name("password")).sendKeys("test123");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".ml-auto")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(2)")).click();
    driver.findElement(By.linkText("Leads")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("lead_company_name")).click();
    driver.findElement(By.id("lead_company_name")).sendKeys("Google");
    driver.findElement(By.id("lead_city")).sendKeys("Bangalore");
    driver.findElement(By.id("lead_address")).sendKeys("Bangalore,karanataka");
    driver.findElement(By.id("lead_country")).sendKeys("india");
    driver.findElement(By.id("lead_state")).sendKeys("karanataka");
    driver.findElement(By.id("lead_pincode")).sendKeys("3456");
    driver.findElement(By.cssSelector(".istar_modal-btn-danger")).click();
    driver.findElement(By.cssSelector("#editLeadModel .close > span")).click();
    driver.findElement(By.cssSelector(".position-relative > .d-flex > .d-flex > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".dropdown-item:nth-child(4)")).click();
  }
}
